services:
  app:
    image: docker.io/jarreybj/radioforest:latest
    # image: ghcr.io/jarrey/radioforest:latest
    container_name: radioforest
    ports:
      # Uncomment and set HTTP_PORT in .env to enable HTTP
      # - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT:-18882}:${HTTPS_PORT:-18882}"
    volumes:
      - ../playlists:/var/www/html/playlists
      - ../backup:/var/www/html/backup
      - ../logs:/var/www/html/logs
      - ../.env:/var/www/html/.env
      # Optional SSL certificate mount:
      - ../ssl:/etc/nginx/ssl
    env_file:
      - ../.env
    restart: unless-stopped
